services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - h2-data:/app/data
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  h2-data:
    driver: local

networks:
  app-network:
    driver: bridge